server:
  port: 9000 
spring:
  # JACKSON
  jackson:
    serialization:
          INDENT_OUTPUT: true
          WRITE_DATES_AS_TIMESTAMPS: false
          WRITE_DURATIONS_AS_TIMESTAMPS: false
  data:
    # MONGO DB
    mongodb:
#      host: ds129146.mlab.com
#      port: 29146
#      password: 123456
#      username: teste
      
      uri: mongodb://teste:naumsei01@ds129146.mlab.com:29146/base-teste