server:
  port: 9000 
spring:
  # JACKSON
  jackson:
    serialization:
          INDENT_OUTPUT: true
          WRITE_DATES_AS_TIMESTAMPS: false
          WRITE_DURATIONS_AS_TIMESTAMPS: false
  data:
  
    # MONGO DB
        
    mongodb:
#      host: ds129146.mlab.com
#      port: 29146
      
      uri: mongodb://teste:naumsei01@ds129146.mlab.com:29146/base-teste
  redis: 
    url: redis-19006.c8.us-east-1-2.ec2.cloud.redislabs.com #127.0.0.1
    port: 19006 #6379
      
  

    
heroku:
  applicationName: ${rootArtifactId}
  info:
    projectName: parent.name
    version: project.version
    timestamp: creation.time.timestamp
  cache:
    timeout:
      defaultExpiration: 30
    names: template-1, template-2

management:
  security:
    enabled: false
  context-path: /actuator
